[package]
name = "dose-response"
version = "0.9.0"
description = "Roguelike game where you play an addict"
authors = ["Tomas Sedovic <tomas@sedovic.cz>"]
homepage = "https://aimlesslygoingforward.com/projects/dose-response-roguelike/"
repository = "https://github.com/tomassedovic/dose-response"
edition = "2018"
license = "GPL-3.0"
build = "build.rs"
exclude = ["scripts/*", "replays/*", "screenshots/*", "ci/*",
           "web-src/*", "*.js", "*.css", "*.html",
           "notes.org", "SAVEDGAME.sav", "out-dir-path", "dose-response.log"]

[[bin]]
name = "dose-response"
path = "src/main.rs"

[dependencies]
bitflags = "1.0"

clap = { version = "2.20.1", optional = true }
serde = "1.0"
serde_derive = "1.0"
serde_json = "1.0"

# We use this to serialise the game save state into a binary format
bincode = "1.0"
line_drawing = "0.7"
log = { version = "0.4.1" }
simplelog = { version = "0.5.2", default-features = false, features = [], optional = true }
chrono = { version = "0.4.0", optional = true }
image = { version = "0.12.2", optional = true }
glium = { version = "0.22", optional = true }
sdl2 = { version = "0.31.0", features = ["bundled"], optional = true }
gl = { version = "0.10", optional = true }
zmq = { version = "0.8", optional = true }

[dependencies.num-rational]
# TODO: update to "0.2.1" which supports Serde 1.0. Problem is, image doesn't
# support it yet and the two versions conflict?
version = "0.1.40"
default-features = false

[target.'cfg(not(target_arch = "wasm32"))'.dependencies]
rand = { version = "0.5", features = ["serde1"], optional = true }

[target.'cfg(target_arch = "wasm32")'.dependencies]
rand = { version = "0.5", default-features = false, features = ["serde1"] }

[build-dependencies]
rusttype = "0.2.1"
image = "0.12.2"


[features]

default = ["sdl", "cli", "replay", "rand", "fullscreen", "cheating", "stats", "verifications"]

fullscreen = []

cheating = []

stats = []

cli = ["clap", "simplelog"]

web = []

replay = ["chrono"]

verifications = []

opengl = ["glium", "image"]

sdl = ["sdl2", "gl", "image"]

sdl-static-link = ["sdl2", "sdl2/static-link"]

remote = ["zmq"]


[profile.release]
codegen-units = 1
# NOTE: this should make the binaries smaller and faster at some compile time cost. Read up on it, profile, verify!
#lto = true
