name: Build and Test Dose Response

on:
  push:
    branches: [ master, 1.1.x, 1.0.x ]
    tags:
      - 'v*.*.*'
  pull_request:
    branches: [ master, 1.1.x, 1.0.x ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build-linux:
    runs-on: ubuntu-latest
    env:
      TARGET_TRIPLE: x86_64-unknown-linux-gnu
      ARCHIVE_EXT: tar.gz
      EXTRA_FEATURES: linux-extra-features
    steps:
    - uses: actions/checkout@v2
    - name: Install build-time dependencies
      run: |
        sudo apt-get update
        sudo apt-get install libasound2-dev
    - name: Build
      run: cargo build --verbose
    - name: Run tests
      run: cargo test --verbose
    - name: Configure AWS Credentials
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: ${{ secrets.AWS_REGION_NAME }}
    - name: Build the release
      run: >
        cargo build --verbose --release --no-default-features
        --features "prod ${{ env.EXTRA_FEATURES }}"
    - name: Package and upload the release
      run: |
        python3 -m pip install --upgrade boto3
        python3 bin/release.py ${{ secrets.AWS_S3_BUCKET_NAME }}

  build-windows:
    runs-on: windows-latest
    env:
      TARGET_TRIPLE: x86_64-pc-windows-msvc
      ARCHIVE_EXT: zip
      EXTRA_FEATURES: windows-extra-features
    steps:
    - uses: actions/checkout@v2
    - run: python -m pip install --upgrade boto3
    - name: Build
      run: cargo build --verbose
    - name: Run tests
      run: cargo test --verbose
    - name: Configure AWS Credentials
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: ${{ secrets.AWS_REGION_NAME }}
    - name: Build the release
      run: >
        cargo build --verbose --release --no-default-features
        --features "prod ${{ env.EXTRA_FEATURES }}"
    - name: Package and upload the release
      run: |
        python3 -m pip install --upgrade boto3
        python3 bin/release.py ${{ secrets.AWS_S3_BUCKET_NAME }}

  build-macos:
    runs-on: macos-latest
    env:
      TARGET_TRIPLE: x86_64-apple-darwin
      ARCHIVE_EXT: zip
      EXTRA_FEATURES: macos-extra-features
    steps:
    - uses: actions/checkout@v2
    - run: python -m pip install --upgrade boto3
    - name: Build
      run: cargo build --verbose
    - name: Run tests
      run: cargo test --verbose
    - name: Configure AWS Credentials
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: ${{ secrets.AWS_REGION_NAME }}
    - name: Build the release
      run: >
        cargo build --verbose --release --no-default-features
        --features "prod ${{ env.EXTRA_FEATURES }}"
    - name: Package and upload the release
      run: |
        python3 -m pip install --upgrade boto3
        python3 bin/release.py ${{ secrets.AWS_S3_BUCKET_NAME }}
